spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: order-service
        uri: lb://order-service
        predicates:
        - Path=/order/**,/order2/**
        
        
      - id: payment-service
        uri: lb://payment-service
        predicates:
        - Path=/payment/**,/payment2/**
        
        
          
server:
  port: 8090
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost